### ISSUE TITLE
add support for secret csi provider

### ISSUE THREAD

**Issue by yuvals41** [Unleash/helm-charts#104]
### Describe the feature request

hello,

i encountered an issue while deploying the helm chart and wanting to use secret store provider aws to safely deploy use the secret in my was secret manager
https://github.com/aws/secrets-store-csi-driver-provider-aws 

I encountered the issue while trying to use the volumes, but I don't see support for it on the values yaml..

i need to use the volume in the deployment yaml like this:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unleash-proxy
spec:
  template:
    spec:
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "unleash-proxy-secret-provider"

```

### Solution suggestions

i would suggest that i can use the values.yaml to change the volumes in the deployment template and maybe even add a secretStoreProvider template in the chart, these solution will clearly solve the issue

Thank you!
