### ISSUE TITLE
Read database connection info from secrets created by Crossplane RDSInstance

### ISSUE THREAD

**Issue by sshort** [Unleash/helm-charts#183]
### Describe the feature request

When using the Crossplane RDSInstance to create a postgresql database for Unleash, the RDSInstance CRD can write the connection information to a secret.  This feature request is to update the unleash Helm chart to read the database connection information from the secret.

The secret looks like this (edited for clarity):

```
apiVersion: v1
kind: Secret
metadata:
  name: <secret name>
  namespace: <secret namespace>
data:
  endpoint: <base64 encoded database endpoint>
  password: <base64 encoded password>
  port: <base64 encoded databse port>
  username: <base64 encoded username>
```

### Background

I am using a Helm chart to deploy an AWS RDS Postgresql database and an Unleash instance that is using that database.  The best way to configure the database settings for Unleash is to read them from the secret created by the Crossplane RDSInstance.

### Solution suggestions

I have created a `databaseSecrets` in the Values file, similar to existingSecrets and iterate through that to set the DATABASE_?? variables.  If databaseSecrets is empty, then the deployment template uses the existing values to create the DATABASE_?? variables
