### ISSUE TITLE
ValidationError when enabling Ingress

### ISSUE THREAD

**Issue by jaboge** [Unleash/helm-charts#22]
Hi,

The chart seems to work as intended until I enable the ingress:

> helm upgrade -i -f values.yaml unleash unleash/unleash

`Error: UPGRADE FAILED: template: unleash/templates/ingress.yaml:35:21: executing "unleash/templates/ingress.yaml" at <.path>: can't evaluate field path in type interface {}`

**values.yaml:**
```
ingress:
  enabled: true #modified!
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: ["/test"] #modified!
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
```
The above values.yaml is an extract from [values.yaml](https://github.com/Unleash/helm-charts/blob/a4b7484bc34b4be4806a22d173de12e628eeb101/charts/unleash/values.yaml), modified as commented above.

Am I doing something wrong or is this a template problem?

**Comment by ivarconr** [comment]
Hi there 👋🏼.

I have not tested this, but I think you need to add paths as an object [according to the k8s docs](https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/service/networking/minimal-ingress.yaml). 

I assume something like this will work:

```yaml
ingress:
  enabled: true #modified!
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: 
      - path: /test
        pathType: prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

```
