### ISSUE TITLE
gh-pages helm repo index.yaml is missing

### ISSUE THREAD

**Issue by monotek** [Unleash/helm-charts#5]
As there was no chart change the release chart action has not released the index.yaml for the helm repo. 
See: https://github.com/Unleash/helm-charts/runs/1921530495?check_suite_focus=true

This can be fixed manually by adding the following index.yaml to the gh-pages branch:

```
apiVersion: v1
entries:
  unleash:
  - apiVersion: v2
    appVersion: 3.11.2
    created: "2021-02-18T20:11:02.176057684+01:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.3.1
    description: Unleash is a open source feature flag & toggle system, that gives you a great overview over all feature toggles across all your applications and services.
    digest: 3e2d59a9e81a67df8592813caa401b9aa9f6c9f2555c8a137b2387d5ce5e75f6
    maintainers:
    - name: evanstucker-hates-2fa
    - email: varconr@gmail.com
      name: ivarconr
    name: unleash
    sources:
    - https://github.com/Unleash/unleash
    - https://github.com/Unleash/unleash-docker
    - https://github.com/Unleash/helm-charts
    type: application
    urls:
    - https://github.com/Unleash/helm-charts/releases/download/unleash-1.0.0/unleash-1.0.0.tgz
    version: 1.0.0
generated: "2021-02-17T20:11:02.167112377+01:00"
``` 

I would have created an pr but i can't see the gh-pages branch even if https://unleash.github.io/helm-charts seems to be created from the repo readme. 

After adding the file to the repo it should be available via: https://unleash.github.io/helm-charts/index.yaml.

If this works repo can be added to https://artifacthub.io/ :)
