### ISSUE TITLE
Missing autoscaling values in values.yaml

### ISSUE THREAD

**Issue by HazemElAgaty** [Unleash/helm-charts#50]
### Describe the bug

This should be a very simple fix. I would have fixed it myself but the contributing guidelines page returns 404.

Basically add the possible values to the autoscaling field in the values.yaml

```yaml
autoscaling:
  enabled: false
  minReplicas: 0
  maxReplicas: 0
  targetCPUUtilizationPercentage: 0
  targetMemoryUtilizationPercentage: 0
```
