### ISSUE TITLE
Error: couldn't find key `postgresql-password` in Secret `unleash-postgresql`

### ISSUE THREAD

**Issue by sturman** [Unleash/helm-charts#69]
### Describe the bug

Wrong Secret key is used to reference `POSTGRESQL_PASSWORD` in Unleash Deployment when using default helm chart values

### Steps to reproduce the bug

1. Add Unleash helm repo
    ```bash
    helm repo add unleash https://docs.getunleash.io/helm-charts
    ```
1. Template Unleash helm chart
    ```bash
    helm template unleash/unleash
    ```
1. Find Deployment of Unleash
1. Check environment variable `POSTGRESQL_PASSWORD` reference

**Actual:**
Deployment manifest:
```yaml
...
spec:
  containers:
    - name: unleash
      env:
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: unleash-postgresql
              key: postgresql-password
...
```

Secret manifest:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: unleash-postgresql
  namespace: "dev"
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-12.1.6
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  postgres-password: "Y2lpTlNIbm9xTA=="
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
```

The problem is that the Secret does not contain `postgresql-password`. It has `postgres-password` key instead.

### Subscription type

Open source

### Hosting type

Self-hosted
