### ISSUE TITLE
Support for PostgreSQL Schema

### ISSUE THREAD

**Issue by roman-supy-io** [Unleash/helm-charts#84]
### Describe the feature request

Please allow specifying `dbConfig.schema` property on `values.yaml`

### Background

Right now it's not possible to configure the chart with custom `schema:` property, therefore all tables get created in `public` schema, which is inconvenient, since there are a lot of system tables and those Unleash creates cannot be determined (e.g. for data migration to another db instance).

### Solution suggestions

```yaml
dbConfig:
  # if postgres dependency chart is used, this needs to be the same value as postgresql.postgresqlDatabase
  database: unleash-db
+ schema: unleash
  ...
```
