### ISSUE TITLE
Deploy chart using an external database not migrate DB

### ISSUE THREAD

**Issue by antoniodinovi** [Unleash/helm-charts#89]
### Describe the bug

When i try to use an external Postgres to deploy on my kubernetes cluster i get this error

```
[2023-07-19T14:23:00.479] [ERROR] server-impl.js - Failed to migrate db OperationalError: getaddrinfo ENOTFOUND unleash-dev-user
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  cause: Error: getaddrinfo ENOTFOUND unleash-dev-user
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'unleash-dev-user'
  },
  isOperational: true,
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'unleash-dev-user'
}
[ERROR] Error: getaddrinfo ENOTFOUND unleash-dev-user
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
```

as the error said, it seems that the configuration does'not consider the host configuration

### Steps to reproduce the bug

This is my helm configuration

The relevant part of my configuration is

```
dbConfig:
  database: unleash-dev
  host: 10.*.*.*
  pass: B*********jDq
  port: 5432
  schema: public
  ssl: false
  useExistingSecret:
    key: ""
    name: ""
  user: unleash-dev-user
.....

postgresql:
  auth:
    database: unleash-dev
    password: ***********
    username: unleash-dev-user
  enabled: false
  fullnameOverride: unleash-postgresql
```

This is the full config
```
affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 0
  minReplicas: 0
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70
configMaps: {}
containerPort: 4242
dbConfig:
  database: unleash-dev
  host: 10.*.*.*
  pass: B*********jDq
  port: 5432
  schema: public
  ssl: false
  useExistingSecret:
    key: ""
    name: ""
  user: unleash-dev-user
env: []
existingSecrets: ""
fullnameOverride: ""
image:
  pullPolicy: Always
  repository: unleashorg/unleash-server
imagePullSecrets: []
ingress:
  annotations: {}
  className: ""
  enabled: false
  hosts:
  - host: chart-example.local
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
initContainers: []
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  path: /health
  timeoutSeconds: 10
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
postgresql:
  auth:
    database: unleash-dev
    password: ***********
    username: unleash-dev-user
  enabled: false
  fullnameOverride: unleash-postgresql
readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  path: /health
  periodSeconds: 10
  successThreshold: 5
  timeoutSeconds: 10
replicaCount: 1
resources: {}
secrets: {}
securityContext: {}
service:
  annotations: {}
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  port: 4242
  type: LoadBalancer
tolerations: []
vpa:
  enabled: false

```

### Expected behavior

I'm expeting that the server start and the migration are applied to my external db

### Unleash version

3.0.1

### Subscription type

Open source

### Hosting type

Self-hosted
